export type CelestialObject = {
    Name: string,
    Type: string,
    RA: string,
    Dec: string,
    Const: string,
    B_Mag: number | null,
    V_Mag: number | null,
    J_Mag: number | null,
    H_Mag: number | null,
    K_Mag: number | null,
    Maj_Ax: number | null,
    Min_Ax: number | null,
    Hubble: string | null,
    M: string | null,
    NGC: string | null,
    IC: string | null,
    Cstar_Names: string | null,
    Identifiers: string | null,
    Common_names: string | null,
    ra_deg: number,
    dec_deg: number,
    magnitude: number
}